#!/bin/bash

#
# NOTE: specify the absolutepath to the directory to use when
#       loading a plugin. '~' expansion is supported.
#

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins

#
# NOTE: if enabled, chunkwm will monitor the specified plugin_dir
#       and automatically reload any '.so' file that is changed.
#

chunkc core::hotload 1
chunkc core::unload tiling.so
chunkc core::unload ffm.so
chunkc core::unload border.so

#
# NOTE: the following are config variables for the chunkwm-tiling plugin.
#

chunkc set global_desktop_mode           bsp
chunkc set 2_desktop_mode                bsp
chunkc set 4_desktop_mode                bsp
chunkc set 5_desktop_mode                bsp
chunkc set 6_desktop_mode                bsp

chunkc set global_desktop_offset_top     4
chunkc set global_desktop_offset_bottom  4
chunkc set global_desktop_offset_left    4
chunkc set global_desktop_offset_right   4
chunkc set global_desktop_offset_gap     2

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                0
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           0
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1

chunkc set window_float_topmost          0
chunkc set window_fade_inactive          0
chunkc set window_fade_alpha             0.75
chunkc set window_fade_duration          0.25
chunkc set window_use_cgs_move           0

chunkc set mouse_modifier                fn

chunkc set preselect_border_color        0xffd75f5f
chunkc set preselect_border_width        5
chunkc set preselect_border_radius       0

chunkc set focused_border_color          0x77cb3dff
chunkc set focused_border_width          4
chunkc set focused_border_radius         0
chunkc set focused_border_skip_floating  0

#chunkc set wallpaper $HOME/Pictures/wall.jpg
#chunkc set wallpaper_blur 100

#
# NOTE: specify plugins to load when chunkwm starts.
#       if chunkc plugin_dir is not set, the absolutepath is necessary.
#

chunkc core::load border.so
chunkc core::load tiling.so
chunkc core::load ffm.so

chunkc tiling::rule --owner qemu --name qemu --state float
chunkc tiling::rule --owner Telegram --name Telegram --state float
chunkc tiling::rule --owner Calculator --state float
chunkc tiling::rule --owner Finder --state float
chunkc tiling::rule --owner Finder --name Copy --state float
#chunkc tiling::rule --owner kitty --state float
#chunkc tiling::rule --owner iTerm2
chunkc tiling::rule --owner QuickTime --state float
chunkc tiling::rule --owner TextEdit --state float
chunkc tiling::rule --owner Mumble --state float
chunkc tiling::rule --owner Stickies --state float

chunkc tiling::rule --owner iTerm2 --name "guake" --state float
chunkc tiling::rule --owner iTerm2 --name "ranger" --state float

chunkc tiling::rule --owner Nimble Commander --state float

# $HOME/.dotfiles/bin/inject
