

" Plug {

    call plug#begin('~/.vim/plugged')

    "Plug 'w0ng/vim-hybrid'
    "Plug 'cocopon/iceberg.vim'
    "Plug 'chriskempson/base16-vim'
    "Plug 'NLKNguyen/papercolor-theme'
    Plug 'ayu-theme/ayu-vim'                " Colorscheme
    Plug 'nanotech/jellybeans.vim'          " Colorscheme

    Plug 'easymotion/vim-easymotion'        " Easy move inside vim
    Plug 'christoomey/vim-tmux-navigator'   " Seamless navigation between tmux panes and vim splits
    Plug 'terryma/vim-multiple-cursors'     " True Sublime Text style multiple selections for Vim

    Plug 'jiangmiao/auto-pairs'             " Auto-completion for quotes, parens, brackets, etc
    Plug 'scrooloose/nerdcommenter'         " Comment functions so powerful—no comment necessary.
    Plug 'tpope/vim-surround'               " Easy mapping to change brakets, parentheses, etc.
    Plug 'junegunn/vim-easy-align'          " A simple, easy-to-use Vim alignment plugin.

    Plug 'tpope/vim-fugitive'               " Git wrapper so awesome, it should be illegal
    Plug 'airblade/vim-gitgutter'           " Git diff on left sidebar

    Plug 'will133/vim-dirdiff'              " Diff directories

    Plug 'justinmk/vim-syntax-extra'        " Vim syntax highlighting for c, bison, flex

    Plug 'xuhdev/vim-latex-live-preview', { 'for': 'tex' }

    Plug 'mbbill/undotree'                  " Left bar with undo tree
    Plug 'majutsushi/tagbar'                " Displays tags in right sidebar
    Plug 'scrooloose/nerdtree'              " A tree explorer plugin for vim.

    Plug 'ronakg/quickr-cscope.vim'
    Plug 'chazy/cscope_maps'

    "Plug 'SirVer/ultisnips'                 " Snippet engine
    Plug 'honza/vim-snippets'               " list of snippets

    "Plug 'wesleyche/SrcExpl'

    "Plug 'ctrlpvim/ctrlp.vim'               " File fuzzy finding
    Plug '~/.dotfiles/src/fzf'
    Plug 'junegunn/fzf.vim'

    Plug 'jremmen/vim-ripgrep'
    Plug 'brooth/far.vim'                   " Find And Replace Vim plugin

    Plug 'elentok/plaintasks.vim'           " Todo like plugin
    Plug 'jceb/vim-orgmode'

    Plug 'dhruvasagar/vim-table-mode'

    Plug 'itchyny/lightline.vim'

    Plug 'vim-scripts/DrawIt'               " Vim draw draw lines left, right, up, down, boxes, etc
    Plug 'fr0zn/markersyntax'
    Plug 'w0rp/ale'

    call plug#end()

" }

" General {

    set background=dark                 " Assume a dark background
    set t_Co=256                        " Set terminal 256 color
    filetype plugin indent on           " Automatically detect file types.
    syntax on                           " Syntax highlighting
    set mousehide                       " Hide the mouse cursor while typing
    autocmd VimEnter * set nospell      " No spell check
    scriptencoding utf-8                " UTF-8 as default encoding

    set rtp+=~/.dotfiles/vim

    " set clipboard=unnamedplus           " System clipboard

    " Always switch to the current file directory
    "autocmd BufEnter * if bufname("") !~ "^\[A-Za-z0-9\]*://" | lcd %:p:h | endif

    " Go last file cursor position
    function! ResCur()
        if line("'\"") <= line("$")
            silent! normal! g`"
            return 1
        endif
    endfunction

    augroup ResCur
        autocmd!
        autocmd BufWinEnter * call ResCur()
    augroup END

    autocmd WinEnter * call s:CloseIfOnlyNerdTreeLeft()

    set autowrite                       " Automatically write a file when leaving a modified buffer
    set shortmess+=filmnrxoOtT          " Abbrev. of messages (avoids 'hit enter')
    set viewoptions=folds,options,cursor,unix,slash " Better Unix / Windows compatibility
    set virtualedit=onemore             " Allow for cursor beyond last character
    set history=1000                    " Store a ton of history (default is 20)
    set timeoutlen=500                  " Time to wait for end of command
    set hidden                          " Allow buffer switching without saving
    set iskeyword-=.                    " '.' is an end of word designator
    set iskeyword-=#                    " '#' is an end of word designator
    set iskeyword-=-                    " '-' is an end of word designator

    set backup                          " Backups are nice ...
    set backupdir=~/.vim/backup          " Backups dir
    set directory=~/.vim/swap            " Swap dir
    set undodir=~/.vim/undo              " Undo dir
    set undofile                        " So is persistent undo ...
    set undolevels=1000                 " Maximum number of changes that can be undone
    set undoreload=10000                " Maximum number lines to save for undo on a buffer reload

    set colorcolumn=80

    set ttyfast                         " Increase vim speed on a tty screen
    set lazyredraw                      " Buffer screen update, speedup scrolling and macro usage

    set csqf=s-,c-,d-,i-,t-,e-          " cscope quick fix

    " use ripgrep
    if executable("rg")
        set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case
    endif

    " quickfix filter
    packadd cfilter
    " quickfix autoclose
    autocmd FileType qf nnoremap <buffer> <CR> <CR>:cclose<CR>
" }

" Vim UI {

    if has("termguicolors")
        set termguicolors               " Enable true color support
    endif

    set background=dark                 " Assume a dark background

    let g:jellybeans_overrides = {
    \ 'NonText': {'guifg': "151515"},
    \}

    let g:jellybeans_use_gui_italics = 0

    if filereadable(expand("$HOME/.vim/plugged/ayu-vim/colors/ayu.vim"))

        if match(readfile(expand("$HOME/.dotfiles/theme")),"light")!=-1
            let g:ayucolor="light"
            colorscheme ayu
        else
            let g:ayucolor="dark"
            colorscheme jellybeans
        endif

        function! g:ToggleBackground()
          if g:ayucolor == 'dark'
            let g:ayucolor="light"
            colorscheme ayu
          else
            let g:ayucolor="dark"
            colorscheme jellybeans
          endif
        endfunction
        nnoremap <silent> <F3> :call g:ToggleBackground()<CR>
    endif

    " vim hardcodes background color erase even if the terminfo file does
    " not contain bce (not to mention that libvte based terminals
    " incorrectly contain bce in their terminfo files). This causes
    " incorrect background rendering when using a color theme with a
    " background color.
    let &t_ut=''
    set t_RV=

    set tabpagemax=15                   " Only show 15 tabs
    set showmode                        " Display the current mode

    set cursorline                      " Highlight current line

    "highlight clear SignColumn          " SignColumn (left) should match background
    "highlight clear LineNr              " Current line number row will have same background color in relative mode

    set ruler                           " Show the ruler
    set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%) " A ruler on steroids
    set showcmd                         " Show partial commands in status line and
                                        " Selected characters/lines in visual mode

    set laststatus=2                        " To always display status bar

    " Broken down into easily includeable segments

    set statusline=%<%f\                    " Filename
    set statusline+=%w%h%m%r                " Options
    set statusline+=\ [%{&ff}/%Y]           " Filetype
    set statusline+=\ [%{getcwd()}]         " Current dir
    set statusline+=%=%-14.(%l,%c%V%)\ %p%% " Right aligned file nav info

    set backspace=indent,eol,start      " Backspace for dummies
    set linespace=0                     " No extra spaces between rows
    set number                          " Line numbers on
    " set relativenumber                  " Relative numbers on
    set showmatch                       " Show matching brackets/parenthesis
    set incsearch                       " Find as you type search
    set hlsearch                        " Highlight search terms
    set winminheight=0                  " Windows can be 0 line high
    " set selection=exclusive             " Selection match what you see
    set wildmenu                        " Show list instead of just completing commands
    set wildmode=list:longest,full      " Command <Tab> completion, list matches, then longest common part, then all.
    set whichwrap=b,s,h,l,<,>,[,]       " Backspace and cursor keys wrap too
    " set scrolljump=5                    " Lines to scroll when cursor leaves screen
    set scrolloff=3                     " Minimum lines to keep above and below cursor
    set foldenable                      " Auto fold code
    set list
    set listchars=tab:›\ ,trail:•,extends:#,nbsp:. " Highlight problematic whitespace

    if has("gui_running")
        set guioptions -=T                   " gui scrollbar
        set guioptions -=r                   " gui scrollbar
        set guioptions -=L                   "remove left-hand scroll bar
        set guioptions -=m                   " gui titlebar
        set guifont=Monospace\ 10
        set titlestring=%f
        set nuw=6
        set clipboard=unnamedplus            " System clipboard
        vmap <C-c> "+y
        vmap <C-x> "+c
        vmap <C-v> c<ESC>"+p
        imap <C-v> <ESC>"+pa
    endif

    autocmd FileType qf 20wincmd_       " Quick fix height

    " Auto-clean fugitive buffers
    autocmd BufReadPost fugitive://* set bufhidden=delete


" }

" Formatting {

    " Strip whitespace {
        " http://stackoverflow.com/questions/356126/how-can-you-automatically-remove-trailing-whitespace-in-vim

        function! StripTrailingWhitespaces()
            let _s=@/
            let l = line(".")
            let c = col(".")
            %s/\s\+$//e
            let @/=_s
            call cursor(l, c)
        endfun
    " }

    set nowrap                          " Do not wrap long lines
    set autoindent                      " Indent at the same level of the previous line
    set shiftwidth=4                    " Use indents of 4 spaces
    set expandtab                       " Tabs are spaces, not tabs
    set tabstop=4                       " An indentation every four columns
    set softtabstop=4                   " Let backspace delete indent
    set nojoinspaces                    " Prevents inserting two spaces after punctuation on a join (J)
    set splitright                      " Puts new vsplit windows to the right of the current
    set splitbelow                      " Puts new split windows to the bottom of the current

    set pastetoggle=<F2>                " pastetoggle (sane indentation on pastes)
    nnoremap <leader>p p`[v`]=          " Reindent pasted text with p key alternative (sickill/vim-pasta)

    " Remove trailings manually like StripTrailingWhitespaces()
    nnoremap <silent> <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>

    " Remove Trailing whitespaces on save
    autocmd BufWritePre * :call StripTrailingWhitespaces()

" }

" Key Mappings {

    fun! SetupCommandAlias(from, to)
      exec 'cnoreabbrev <expr> '.a:from
            \ .' ((getcmdtype() is# ":" && getcmdline() is# "'.a:from.'")'
            \ .'? ("'.a:to.'") : ("'.a:from.'"))'
    endfun

    " Remap our leader key
    let mapleader = ','

    " Faster switch between split windows
    map <C-j> <C-w>j<C-w>_
    map <C-k> <C-w>k<C-w>_
    map <C-l> <C-w>l<C-w>_
    map <C-h> <C-w>h<C-w>_

    " Wrapped lines goes down/up to next row, rather than next line in file.
    noremap j gj
    noremap k gk

    " Correct most common errors while typing a command
    command! -bang -nargs=* -complete=file E e<bang> <args>
    command! -bang -nargs=* -complete=file W w<bang> <args>
    command! -bang -nargs=* -complete=file Wq wq<bang> <args>
    command! -bang -nargs=* -complete=file WQ wq<bang> <args>
    command! -bang Wa wa<bang>
    command! -bang WA wa<bang>
    command! -bang Q q<bang>
    command! -bang QA qa<bang>
    command! -bang Qa qa<bang>

    " Yank full line
    nnoremap Y yy

    " Clear search selection
    nmap <silent> <leader>/ :nohlsearch<CR>

    " Visual shifting (does not exit Visual mode)
    vnoremap < <gv
    vnoremap > >gv

    " Allow using the repeat operator with a visual selection (!)
    vnoremap . :normal .<CR>

    " For when you forget to sudo.. Really Write the file.
    cmap w!! w !sudo tee % >/dev/null

    " Map <Leader>tt to display all lines with keyword under cursor
    " and ask which one to jump to
    nmap <leader>tt [I:let nr = input("Which one: ")<Bar>exe "normal " . nr ."[\t"<CR>

    " Easier horizontal scrolling
    map zl zL
    map zh zH

    " Easier buffer change
    map gn :bn<cr>
    map gp :bp<cr>
    map <leader>d :bd<cr>

    " Changed base command to work with windows
    nnoremap <leader>w <c-w>

    " Fast save and exit
    map <leader>s :w<cr>
    map <leader>q :q<cr>
    map <leader>wq :wq<cr>

    nnoremap <C-a> _
    nnoremap <C-e> <End>

    " quickfix
    unmap \p
    command GREP :execute 'vimgrep! /'.expand('<cword>').'/j '.expand('%') | :cw
    map \ :GREP<cr>
    map # :GREP<cr>

    " Grep override with ripgrep
    call SetupCommandAlias("grep","Rg")

    nnoremap <silent> [q :cprevious<CR>
    nnoremap <silent> ]q :cnext<CR>
    nnoremap <leader>o :copen<cr>

" }

" Plugins {

    " vim-airline {
        " let g:airline_left_sep='›'  " Slightly fancier than '>'
        " let g:airline_right_sep='‹' " Slightly fancier than '<'

        " let g:airline_powerline_fonts = 1
        " let g:airline_theme = 'gruvbox'

        " let g:indent_guides_enable_on_vim_startup = 0
        " let g:airline#extensions#tabline#enabled = 1
        "" Show just the filename
        " let g:airline#extensions#tabline#fnamemod = ':t'
        " let g:airline#extensions#bufferline#enabled = 0

    " }

    " NerdTree {
        map <silent> <leader>e :NERDTreeToggle<CR>

        " let NERDTreeShowBookmarks=1
        let NERDTreeIgnore=['\.py[cd]$', '\~$', '\.swo$', '\.swp$', '^\.git$', '^\.hg$', '^\.svn$', '\.bzr$','\.DS_Store']
        " Close all open buffers on entering a window if the only
        " buffer that's left is the NERDTree buffer
        function! s:CloseIfOnlyNerdTreeLeft()
          if exists("t:NERDTreeBufName")
            if bufwinnr(t:NERDTreeBufName) != -1
              if winnr("$") == 1
                q
              endif
            endif
          endif
        endfunction
        " let NERDTreeChDirMode=0
        " let NERDTreeQuitOnOpen=1
        " let NERDTreeMouseMode=2
        " let NERDTreeShowHidden=1
        " let NERDTreeKeepTreeInNewTab=1
        " let g:nerdtree_tabs_open_on_gui_startup=0
    " }

    " auto-pairs {

        " Shortcut to jump out of the pair
        let g:AutoPairsShortcutJump = '<S-Tab>'

    " }

    " UndoTree {

        nnoremap <silent> <leader>u :UndotreeToggle<cr>
        let g:undotree_SetFocusWhenToggle=1

    " }

    " YouCompleteMe {

        " let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'

        " " make YCM compatible with UltiSnips (using supertab)
        " let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
        " let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
        " let g:SuperTabDefaultCompletionType = '<C-n>'

        " let g:ycm_collect_identifiers_from_tags_files = 1

        " let g:ycm_error_symbol = '✘'
        " let g:ycm_warning_symbol = '⚠️'

    " }

    " UltiSnips {

        " better key bindings for UltiSnipsExpandTrigger
        let g:UltiSnipsExpandTrigger = "<tab>"
        let g:UltiSnipsJumpForwardTrigger = "<tab>"
        let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"

    " }

    " Nerdcommenter {

        " Add spaces after comment delimiters by default
        " let g:NERDSpaceDelims = 1
        " Enable trimming of trailing whitespace when uncommenting
        " let g:NERDTrimTrailingWhitespace = 1
        " Align line-wise comment delimiters flush left instead of following
        " code indentation
        " let g:NERDDefaultAlign = 'left'

    " }

    " Vim-multiple-cursors{

        let g:multi_cursor_use_default_mapping=0
        let g:multi_cursor_next_key='<C-d>'               " Mapped like sublime key
        let g:multi_cursor_prev_key='<C-p>'               " Default
        let g:multi_cursor_skip_key='<C-x>'               " Default
        let g:multi_cursor_quit_key='<C-c>'               " Exit mode key, It doesn't always work
        nnoremap <silent> <C-c> :call multiple_cursors#quit()<CR>  " Faster mode exit

    " }

    " TagBar {
        nnoremap <silent> <leader>t :TagbarToggle<CR>
        let g:tagbar_autofocus = 1
        let g:tagbar_autoclose = 1
    "}

    " Surround {
        let g:surround_indent = 1
    " }

    " Source Explorer {
        " The switch of the Source Explorer
        "nmap <silent> <leader>r :SrcExplToggle<CR>
        " Set "Enter" key to jump into the exact definition context
        "let g:SrcExpl_jumpKey = "<ENTER>"
    " }

    " Ctrl-p {
        "nnoremap <silent> <leader>b :CtrlPBuffer<cr>
    " }

    " FZF {
        let g:fzf_layout = { 'down': '~20%' }
        let $FZF_DEFAULT_COMMAND ='fd --type f'
        nnoremap <silent> <C-p> :FZF -m<cr>
        nnoremap <silent> <leader>b :Buffers<cr>
        imap <C-f> <plug>(fzf-complete-path)
    " }

    " vim-ripgrep {
        nnoremap <silent> <leader>g :Rg<cr>
    " }

    " vim-easy-align {
        " Start interactive EasyAlign in visual mode (e.g. vipga)
        xmap <Leader>a <Plug>(EasyAlign)

        " Start interactive EasyAlign for a motion/text object (e.g. gaip)
        nmap <Leader>a <Plug>(EasyAlign)
    " }

    " EasyMotion {
        map <Leader>j <Plug>(easymotion-j)
        map <Leader>k <Plug>(easymotion-k)
        "map  / <Plug>(easymotion-sn)
        "omap / <Plug>(easymotion-tn)
    " }

    " ALE {
        " Run on save
        let g:ale_lint_on_text_changed = 'never'
        " if you don't want linters to run on opening a file
        let g:ale_lint_on_enter = 0
    " }

    " LightLine {
        let g:lightline = {
          \ 'active' : {
          \     'left': [ [ 'mode', 'paste' ], [ 'readonly', 'relativepath', 'modified' ] ]
          \ },
          \ 'colorscheme': 'jellybeans',
          \ 'component': {
          \   'lineinfo': "%{line('.')}/%{line('$')} (%2v)",
          \ },
          \ }
    " }

    " GitGutter {
        nmap ]h <Plug>GitGutterNextHunk
        nmap [h <Plug>GitGutterPrevHunk
        autocmd BufWritePost * GitGutter
    " }

    " markersyntax {
        let g:markersyntaxWords      = ['TODO', 'FIXME', 'BUG', 'NOTE']
        let g:markersyntaxColors     = ['#fabd2f', '#fe8019', '#fb4934', '#b8bb26']
    " }

    " vim-latex-preview {
        "let g:livepreview_previewer = 'open -a Skim'
        let g:livepreview_previewer = 'xpdf'
    " }

    " UltiSnips {
        let g:UltiSnipsEditSplit="vertical"
        let g:UltiSnipsSnippetsDir = "~/.dotfiles/vim/snips"
        let g:UltiSnipsSnippetDirectories=["UltiSnips", "snips"]
    " }

    " IndentLine {
        let g:indentLine_char_list = ['|', '¦', '┆', '┊']
        let g:indentLine_showFirstIndentLevel = 1
        let g:indentLine_setColors = 0
    " }

    " Quickr_cscope {
        let g:quickr_cscope_keymaps = 0
        "vnoremap <leader>e            <Plug>(quickr_cscope_egrep)
        vnoremap <leader>d            <Plug>(quickr_cscope_functions)
        vnoremap <leader>t            <Plug>(quickr_cscope_text)
        vnoremap <leader>i            <Plug>(quickr_cscope_includes)
        vnoremap <leader>f            <Plug>(quickr_cscope_files)
        vnoremap <leader>c            <Plug>(quickr_cscope_callers)
        vnoremap <leader>s            <Plug>(quickr_cscope_symbols)
        vnoremap <leader>g            <Plug>(quickr_cscope_global)
        "nmap <leader>e            <Plug>(quickr_cscope_egrep)
        nmap <leader>d            <Plug>(quickr_cscope_functions)
        nmap <leader>i            <Plug>(quickr_cscope_includes)
        nmap <leader>f            <Plug>(quickr_cscope_files)
        nmap <leader>c            <Plug>(quickr_cscope_callers)
        nmap <leader>s            <Plug>(quickr_cscope_symbols)
    " }

" }
