# Path to dotfiles
DOTFILE_PATH=$HOME/.dotfiles
SCRIPTS_PATH=$DOTFILE_PATH/scripts
ZSH_CONFIG_PATH=$DOTFILE_PATH/zsh

unamestr=`uname`

# Function to add to path
. $SCRIPTS_PATH/path.sh

pathadd "$HOME/.dotfiles/bin" after

# Antigen
. $ZSH_CONFIG_PATH/antigen.sh

# Load ZSHRC config
. $ZSH_CONFIG_PATH/all_zshrc.conf

# MacOS configs
if [[ "$unamestr" == "Darwin" ]]; then
    . $ZSH_CONFIG_PATH/macos_zshrc.conf
else
# Linux configs
    . $ZSH_CONFIG_PATH/linux_zshrc.conf
    # Docker configs
    if [ -f /.dockerenv ]; then
        . $ZSH_CONFIG_PATH/docker_zshrc.conf
    fi
fi

# FZF config
[ -f ~/.fzf.zsh ] && . ~/.fzf.zsh

. $SCRIPTS_PATH/env.sh
