# Path to dotfiles
DOTFILE_PATH=$HOME/.dotfiles
SCRIPTS_PATH=$DOTFILE_PATH/scripts
ZSH_CONFIG_PATH=$DOTFILE_PATH/zsh

# Antigen
source ~/.antigen/antigen.zsh
antigen use oh-my-zsh
antigen theme fr0zn/simplezsh
# Plugins
antigen bundle rupa/z
antigen bundle colored-man-pages
antigen bundle encode64
antigen apply


unamestr=`uname`

# Load ZSHRC config
source $ZSH_CONFIG_PATH/all_zshrc.conf

# MacOS configs
if [[ "$unamestr" == "Darwin" ]]; then
    source $ZSH_CONFIG_PATH/macos_zshrc.conf
else
# Linux configs
    source $ZSH_CONFIG_PATH/linux_zshrc.conf
    # Docker configs
    if [ -f /.dockerenv ]; then
        source $ZSH_CONFIG_PATH/docker_zshrc.conf
    fi
fi

# FZF config
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# pyenv PATH and virtualenv PATH
eval "$(pyenv init -)"
#eval "$(pyenv virtualenv-init -)"
. $SCRIPTS_PATH/pyenv_version.sh
