# Path to dotfiles
DOTFILE_PATH=$HOME/.dotfiles
SCRIPTS_PATH=$DOTFILE_PATH/scripts
BASH_CONFIG_PATH=$DOTFILE_PATH/bash

unamestr=`uname`

# Load BASHRC config
source $BASH_CONFIG_PATH/all_bashrc

out=$(cat /proc/cpuinfo | grep hypervisor)
if [[ "$?" -eq "0" ]];then # inside hypervisor
    source $BASH_CONFIG_PATH/vm_bashrc
fi

source $BASH_CONFIG_PATH/z.sh

source $SCRIPTS_PATH/env.sh

# FZF config
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
