# Path to dotfiles
DOTFILE_PATH=$HOME/.dotfiles
SCRIPTS_PATH=$DOTFILE_PATH/scripts
SHELLS_PATH=$DOTFILE_PATH/shells
CONFIG_PATH=$DOTFILE_PATH/bash

. $SHELLS_PATH/allrc

# FZF config
[ -f ~/.fzf.bash ] && . ~/.fzf.bash
